# Generated by Django 2.2.5 on 2020-03-16 10:15

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Number', 'Sign Language Number'), ('Alphabet', 'Sign Language Alphabet')], default='Sign Language Hand Gesture Digit', max_length=256)),
                ('uploads', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[200, 200], upload_to='uploaded_images/')),
            ],
        ),
    ]
