# Generated by Django 2.2.5 on 2020-03-18 06:34

from django.db import migrations, models
import django_resized.forms
import gisa.models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='segment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploads', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[200, 200], storage=gisa.models.OverwriteStorage(), upload_to='segmented_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='uploads',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[200, 200], storage=gisa.models.OverwriteStorage(), upload_to='uploaded_images/'),
        ),
    ]
