# Generated by Django 2.2.5 on 2020-03-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0002_auto_20200318_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='category',
            field=models.CharField(choices=[('Number', 'Sign Language Number'), ('Alphabet', 'Sign Language Alphabet')], default='Sign Language Hand Gesture Digit', max_length=256),
        ),
    ]
