# Generated by Django 2.2.5 on 2020-03-18 13:55

from django.db import migrations
import django_resized.forms
import gisa.models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0004_auto_20200318_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='uploads',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[200, 200], storage=gisa.models.OverwriteStorage(), upload_to='home/manav/Desktop/project/media/segmented_images/'),
        ),
    ]
